import { IMenus } from '../interfaces/common/i-menus';

export const MenuConstant: IMenus[] = [
  // {
  //   path: '/',
  //   title: 'Dashboard',
  //   roles: ['EM', 'PC', 'CU'],
  //   exact: true,
  //   icon: 'fas fa-tachometer-alt',
  // },
  {
    path: '/my-profile',
    title: 'My Profile',
    roles: ['EM', 'PC', 'CU'],
    exact: false,
    icon: 'fas fa-user',
  },
  {
    path: '/users',
    title: 'Users',
    roles: ['AD'],
    exact: false,
    icon: 'fas fa-users',
  },
  {
    path: '/roles',
    title: 'Roles',
    roles: ['AD'],
    exact: false,
    icon: 'fas fa-user-secret',
  },
  {
    path: '/master',
    title: 'Master',
    roles: ['EM'],
    exact: false,
    icon: 'fa fa-home',
    child: [
      {
        path: '/master/car',
        title: 'Cars',
        roles: ['EM'],
        exact: false,
        icon: 'fa fa-car',
      },
      {
        path: '/master/category',
        title: 'Category',
        roles: ['EM'],
        exact: false,
        icon: 'fas fa-folder',
      },
      {
        path: '/master/insurance-type',
        title: 'Insurance Type',
        roles: ['EM'],
        exact: false,
        icon: 'fas fa-file',
      },
      {
        path: '/master/zone',
        title: 'Zone',
        roles: ['EM'],
        exact: false,
        icon: 'fas fa-globe',
      },
      {
        path: '/master/region',
        title: 'Region',
        roles: ['EM'],
        exact: false,
        icon: 'fas fa-map-marker',
      },
    ],
  },
  {
    path: '/customer',
    title: 'Customer Request',
    roles: ['EM', 'PC', 'CU'],
    exact: false,
    icon: 'fas fa-users',
  },
  {
    path: '/partner',
    title: 'Partner',
    roles: ['PR', 'AD', 'EM'],
    exact: false,
    icon: 'fa fa-building',
    child: [
      {
        path: '/partner/partner',
        title: 'Partner',
        roles: ['AD', 'EM'],
        exact: false,
        icon: 'fa fa-car',
      },
      {
        path: '/partner/workorder',
        title: 'Partner Work Order',
        roles: ['PR', 'EM'],
        exact: false,
        icon: 'fa fa-briefcase',
      },
    ],
  },
  {
    path: '/so',
    title: 'Service Order',
    roles: ['EM'],
    exact: false,
    icon: 'fas fa-cogs',
  },
];
