export enum PartnerEntity{
    PARTNER = "PARTNER",
    PARTNER_CONTACT = "PARTNER CONTACT",
    PARTNER_AREA_WORKGROUP = "PARTNER AREA WORKGROUP",
    CLAIM_ASSET_SPAREPARTS = "CLAIM ASSET SPAREPARTS",
    CLAIM_ASSET_EVIDENCE = "CLAIM ASSET EVIDENCE"
}